source 'https://rubygems.org'
gem "non-stupid-digest-assets"
gem 'protected_attributes', '~> 1.0.5'
gem 'delayed_job_active_record'
gem 'rails', '4.0.4'
gem 'sqlite3'
gem 'gon'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bcrypt-ruby', '3.1.2'
gem 'paperclip', github: 'thoughtbot/paperclip'
gem 'haml'
gem 'simple_form'
gem 'mysql2'
gem 'capistrano'
gem 'capistrano-bundler'
gem 'capistrano-rails'
gem 'inherited_resources'
gem 'twitter'
gem 'stripe'
gem 'feedjira'
gem 'nokogiri'
gem 'fullcontact'
gem 'pry'
gem 'sendgrid'
gem 'sendgrid_webapi', '0.0.3'
gem 'mechanize'
gem 'geocoder'
gem 'chosen-rails'
